app:
  Name: snake
  Version: 1.0.0
  PprofPort: :5555
  Mode: debug                 # debug, release, test
  JwtSecret: JWT_SECRET
  JwtTimeout: 86400
  CookieName: jwt-token
  SSL: true
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false

Http:
  Addr: :8080
  ReadTimeout: 5
  WriteTimeout: 5
Grpc:
  Addr: :9090
  ReadTimeout: 5
  WriteTimeout: 5

logger:
  Development: false
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json                          # json or console
  Level: info                             # 日志级别，DEBUG, INFO, WARN, ERROR, FATAL
  Name: snake
  Writers: console                        # 有2个可选项：file,console 选择file会将日志记录到logger_file指定的日志文件中，选择console会将日志输出到标准输出，当然也可以两者同时选择
  LoggerFile: /tmp/log/snake.log
  LoggerWarnFile: /tmp/log/snake.wf.log
  LoggerErrorFile: /tmp/log/snake.err.log
  LogRollingPolicy: daily
  LogRotateDate: 1
  LogRotateSize: 1
  LogBackupCount: 7

mysql:
  Name: snake                     # 数据库名称
  Addr: localhost:3306            # 如果是 docker,可以替换为 对应的服务名称，eg: db:3306
  UserName: root
  Password: 123456
  ShowLog: true                   # 是否打印SQL日志
  MaxIdleConn: 10                 # 最大闲置的连接数，0意味着使用默认的大小2， 小于0表示不使用连接池
  MaxOpenConn: 60                 # 最大打开的连接数, 需要小于数据库配置中的max_connections数
  ConnMaxLifeTime: 60m            # 单个连接最大存活时间，建议设置比数据库超时时长(wait_timeout)稍小一些

redis:
  Addr: 127.0.0.1:6379
  Password: ""
  DB: 0
  MinIdleConn: 200
  DialTimeout: 60s
  ReadTimeout: 500ms
  WriteTimeout: 500ms
  PoolSize: 12000
  PoolTimeout: 240

email:
  Host: SMTP_HOST       # SMTP地址
  Port: 25              # 端口
  Username: USER        # 用户名
  Password: PASSWORD    # 密码
  Name: snake           # 发送者名称
  Address: SEND_EMAIL   # 发送者邮箱
  ReplyTo: EMAIL       # 回复地址
  KeepAlive: 30         # 连接保持时长

website:
  Name: snake
  Domain: http://snake.com
  Secret: abcdefg
  Static: /data/static

cookie:
  Name: jwt-token
  MaxAge: 86400
  Secure: false
  HttpOnly: true
  Domain: http://snake.com
  Secret: abcdefg

qiniu:
  AccessKey: ACCESS_KEY
  SecretKey: SECRET_KEY
  CdnURL: http://cdn.snake.com
  SignatureID: signature_id  # 短信签名id
  TemplateID: template_id    # 模板id

metrics:
  Url: 0.0.0.0:7070
  ServiceName: api

MongoDB:
  URI: "mongodb://localhost:27017"
  User: "admin"
  Password: "admin"
  DB: "snake"

trace:
  # trace config
  ServiceName: "snake"
  TraceAgent: "jaeger"
  OpenDebug: "false"

  Zipkin:
    HTTPEndpoint: "http://127.0.0.1:9411/api/v2/spans"
    SameSpan: false
    ID128Bit: true
    SampleRate: "1.0"
  Jaeger:
    SamplingServerURL: "http://127.0.0.1:5778/sampling"
    SamplingType: "const"
    SamplingParam: "1.0"
    LocalAgentHostPort: "127.0.0.1:6831"
    Propagation: "jaeger"
    Gen128Bit: true
    TraceContextHeaderName: "uber-trace-id"
    CollectorEndpoint: "http://localhost:14268/api/traces"
    CollectorUser: ""
    CollectorPassword: ""

  # Elastic, only useful when TraceAgent is elastic
  Elastic:
    ServerURL: "http://127.0.0.1:8200"
    SecretToken: ""
