app:
  Name: snake
  Version: 1.0.0
  Port: :8080
  PprofPort: :5555
  Mode: debug                 # debug, release, test
  JwtSecret: JWT_SECRET
  JwtTimeout: 86400
  CookieName: jwt-token
  ReadTimeout: 5
  WriteTimeout: 5
  SSL: true
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info
  Name: snake
  Writers: file,stdout
  LoggerFile: /tmp/log/snake.log
  LoggerWarnFile: /tmp/log/snake.wf.log
  LoggerErrorFile: /tmp/log/snake.err.log
  LogRollingPolicy: daily
  LogRotateDate: 1
  LogRotateSize: 1
  LogBackupCount: 7

mysql:
  Name: snake                     # 数据库名称
  Addr: db:3306                   # 如果是 docker,可以替换为 对应的服务名称，eg: db:3306
  UserName: root
  Password: 123456
  ShowLog: true                   # 是否打印SQL日志
  MaxIdleConn: 10                 # 最大闲置的连接数，0意味着使用默认的大小2， 小于0表示不使用连接池
  MaxOpenConn: 60                 # 最大打开的连接数, 需要小于数据库配置中的max_connections数
  ConnMaxLifeTime: 60m            # 单个连接最大存活时间，建议设置比数据库超时时长(wait_timeout)稍小一些

redis:
  Addr: redis:6379
  Password: ""
  DB: 0
  MinIdleConn: 200
  DialTimeout: 60s
  ReadTimeout: 500ms
  WriteTimeout: 500ms
  PoolSize: 12000
  PoolTimeout: 240

cache:
  Driver: "redis"                 # 缓存驱动，可以选memory、redis, 默认redis
  Prefix: "snake:"                # cache key前缀，一般为项目名称即可

email:
  Host: SMTP_HOST       # SMTP地址
  Port: 25              # 端口
  Username: USER        # 用户名
  Password: PASSWORD    # 密码
  Name: snake           # 发送者名称
  Address: SEND_EMAIL   # 发送者邮箱
  ReplyTo: EMAIL       # 回复地址
  KeepAlive: 30         # 连接保持时长

website:
  Name: snake
  Domain: http://snake.com
  Secret: abcdefg
  Static: /data/static

cookie:
  Name: jwt-token
  MaxAge: 86400
  Secure: false
  HttpOnly: true
  Domain: http://snake.com
  Secret: abcdefg

qiniu:
  AccessKey: ACCESS_KEY
  SecretKey: SECRET_KEY
  CdnURL: http://cdn.snake.com
  SignatureID: signature_id  # 短信签名id
  TemplateID: template_id    # 模板id

metrics:
  Url: 0.0.0.0:7070
  ServiceName: api

jaeger:
  Host: localhost:6831
  ServiceName: REST_API
  LogSpans: false